language: go
env:
  - GO111MODULE=off
services:
- docker
before_install:
- docker pull centrifugo/centrifugo
- docker run -d -p 8000:8000 centrifugo/centrifugo centrifugo --client_insecure
install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure
go:
  - "1.13.x"
  - "1.12.x"
  - "tip"
script: go test -v
